### PR TITLE
merge period

### PR DESCRIPTION
**Pull request by stevieflow**
~~Adaptation of merge_indicator.py that will merge periods that share the same indicator narrative~~

Enhancement of the merge_indicator script, which now ensures that all results are retained within a single activity (if multiple exist in an activities file), and then combines all of the periods for each indicator.

Closing #3

### CODE REVIEW

**Comment by stevieflow** [comment]
Does this still need review @Lathrisk ?

**Comment by Lathrisk** [comment]
@stevieflow Yes, I think it does.
@Bjwebb @kindly could either of you take a look at this?

**Comment by stevieflow** [comment]
PLease can we merge this?  I just used the master branch to merge indicators, thinking that the code was already merge :(

**Comment by Lathrisk** [comment]
I must have missed the approval notification on the 26th.

**Pull request merged**
